import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { parseText, analyze, toCSV, toHTML } from '../src/analyzer.js';
const root=new URL('../',import.meta.url);
await mkdir(new URL('fixtures/',root),{recursive:true});
await mkdir(new URL('reports/',root),{recursive:true});
const start=Date.parse('2026-08-01T12:00:00Z');
const rows=[];
const add=(s,event,ip,user)=>rows.push({timestamp:new Date(start+s*1000).toISOString(),event,src_ip:ip,user,host:'lab-linux-01'});
for(const s of [0,20,40,60,80])add(s,'failure','192.0.2.10','lab_alex');
add(100,'success','192.0.2.10','lab_alex');
for(const s of [0,400,800,1200,1600])add(s,'failure','192.0.2.20','lab_morgan');
add(1800,'success','192.0.2.20','lab_morgan');
for(const s of [10,50,110])add(s,'success','192.0.2.30','lab_jordan');
const source='# SYNTHETIC fixtures, not captured traffic. RFC 5737 example addresses.\n'+rows.map(x=>JSON.stringify(x)).join('\n')+'\n';
await writeFile(new URL('fixtures/auth-demo.jsonl',root),source);
const parsed=parseText(source),report=analyze(parsed.events);
report.provenance='Controlled synthetic authentication fixture. Results are a local software demonstration, not a production incident.';
report.parseErrors={errorCount:parsed.errorCount,examples:parsed.errors};
const expected={alertedIPs:['192.0.2.10'],normalIPs:['192.0.2.20','192.0.2.30'],expectedRules:['failure_burst','success_after_burst']};
assert.deepEqual([...new Set(report.alerts.map(a=>a.ip))],expected.alertedIPs);
assert.deepEqual(report.alerts.map(a=>a.rule),expected.expectedRules);
assert.equal(parsed.errorCount,0);
await writeFile(new URL('fixtures/expected.json',root),JSON.stringify(expected,null,2));
await writeFile(new URL('reports/demo.json',root),JSON.stringify(report,null,2));
await writeFile(new URL('reports/demo.csv',root),toCSV(report));
await writeFile(new URL('reports/demo.html',root),toHTML(report,'Security Log Analyzer - controlled demo'));
console.log(JSON.stringify(report.summary));
console.log('Report: reports/demo.html');
